/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Monster monster1 = new Monster(0, 3);
    System.out.println(monster1.toString());
    Monster monster2 = new Monster(1, 2);
    System.out.println(monster2.toString());
    Monster monster3 = new Monster(2, 1);
    System.out.println(monster3.toString());
    Monster monster4 = new Monster(3, 0);
    System.out.println(monster4.toString());
  }
}
